# Standard training pipeline (matches training_config.yaml)

parameters:
  epochs: 10
  n_samples: 11000
  country: ""
  detect_drift: false
  simulate_drift: false

steps:
  load_data:
    enable_cache: true
  analyze_data:
    enable_cache: false
  filter_by_country:
    enable_cache: true
  clean_data:
    enable_cache: true
  train_model:
    docker:
      requirements: "requirements.txt"
      python_package_installer: "uv"
      build_config:
        build_options:
          platform: linux/amd64
    enable_cache: false
  generate_data_analysis_report:
    enable_cache: false
